### ISSUE TITLE
Color field required

### ISSUE THREAD

**Issue by kirchaj** [ConsoleTVs/Laralum#1]
When I am adding a new role it keeps flashing the error "color field required".  there doesn't appear to be a place to select a color.

I love your work btw.  I think I can use your work in a project of mine.  thanks for the efforts.
Tony

**Comment by ConsoleTVs** [comment]
Hello! i did not expect that error, it have an easy fix tho, you have a simple array settings in the RoleController, where you can see the validator settings, simply remove the color line from there, or add a "color" field in the role migration :p 

EDIT: This will be fixed today night!

**Comment by ConsoleTVs** [comment]
The point is that you can add fields in the database and you'll be able to edit it without adding any code, :p

The lines you need to edit are:

'color' => 'required|unique:roles', (App\Http\ControllersRolesController line 63)
and
'color' => 'sometimes|required|unique:roles,color,'.$role->id,  (App\Http\ControllersRolesController line 77)

Simply remove them!

**Comment by ConsoleTVs** [comment]
@kirchaj Thanks for pointing that out, it's fixed in [today's relese 1.0.3](https://github.com/ConsoleTVs/Laralum/releases/tag/1.0.3)!
