### ISSUE TITLE
is this project free to use?

### ISSUE THREAD

**Issue by poseso** [ConsoleTVs/Laralum#2]
csanchez@Carloss-iMac:/Applications/MAMP/htdocs/laralum$ php artisan migrate
Migration table created successfully.

  [ErrorException]  
  Trying to get property of non-object  

When i run php artisan migrate i get this error, and if i visit the site i get Internal Server Error,

I'd like to see the project in action if it's possible

**Comment by poseso** [comment]
Oh veo en tu twitter que hablas español, mas facil para comunicarse

**Comment by ConsoleTVs** [comment]
Hola poseso, en unos dias (si no es mañana) publicare la nueva version de laralum, la 2.0, la qual usa Laravel 5.3, y funciona con instalador, si no es mucho pedir, podrias esperar un par de dias?

Si, es totalmente gratuito

**Comment by ConsoleTVs** [comment]
Aqui tienes una foto de como será: https://i.gyazo.com/3f6cb23697d55fbfcff5b9fdf1f811a7.png

**Comment by ConsoleTVs** [comment]
A decir mas, tengo un amigo que traducira la applicacion a español y catalan, por lo que, namas salir la version, unos dias despues la actualizare para poner los idiomas!!

**Comment by poseso** [comment]
Por supuesto erik que no tengo inconvenientes, de hecho si puedo ser de ayuda para tu proyecto encantado estare de aportar mis conocimientos al proyecto, y tambien para las traducciones al español

**Comment by ConsoleTVs** [comment]
Ahora mismo soy el unico que esta trabajando en esto, asi que si estas familiarizado con laravel (estoy acabando de leer la documentacion) y te gustaria ayudar tengo muchissimas ideas que son faciles de implementar con lo que ya tengo hecho. Ire documentando poco a poco el trabajo que ya tengo hecho para que cualquier persona sea capaz de ayudar o de saber utilizar el sistema. De momento tengo pensadas las siguientes cosas:
- Documentar todo 
- Redes sociales (Añadir redes sociales utilizando OAuth2 o las APIs)
- Crear una API interna (para que tu sistema tenga una REST API para que, si la habilitas, se pueda usar)
- Foro utilizando las tablas existentes de los blogs (post = post inicial, comments = posts relativos al post inicial)
- Notificaciones en vivo (utilizar la API interna para usarla con jQuery pudiendo mostrar el vivo las notificaciones de usuario)
- Estadisticas en vivo (utilizar la API interna para usarla con jQuery pudiendo actualizar los graficos cada segundo (por ejemplo) y asi mostrar en tiempo real las estadisticas)
- Estadisticas generales (de fecha a fecha mostrar todo lo posible)
- Usar las queues de laravel para hacer mas rapida la app (enviando los correos en segundo plano por ejemplo)
- Crear estadisticas mensuales enviadas al correo cada mes (o tareas realizadas cada cierto tiempo) usando las queues
- Gestion de facturas
- Implementar paypal u otros procesadores de pago
- Hacer tienda online usando los 2 ultimos puntos

Estas solo son algunas de las ideas, pero Laralum tiene muchas cosas para facilitar el trabajo, lo digo porque ya he pensado en todo esto, es un proyecto que se adapta a la base de datos por lo que crear los formularios de creacion / edicion de cosas solo hace falta 1 linea, y para crear graficos tambien (tengo 4 funciones para crear graficos de 4 tipos diferentes - de linea, de barras, de queso y geograficos - los quales con una linea ya los tienes en la pagina).

Si te ves capaz de ayudar o te gustaria saber mas podemos hablar mas tranquilamente por algun  lugar!

Gracias por el interes en el proyecto!

**Comment by poseso** [comment]
Si, me gustaria ayudar, cuando tengas disponibilidad dejame saber para que lo podamos conversar, me gustaria aportar al proyecto

**Comment by ConsoleTVs** [comment]
Suelo estas bastante disponible, podemos hablar por skype en detalle de todo, mi skype es: ErikCampobadal

Si prefieres otro tipo de metodo para conversarlo en detalle dimelo que por mi ningun problema!

**Comment by poseso** [comment]
Pues podria ser a traves de hangouts? te parece ?

**Comment by ConsoleTVs** [comment]
Hmm realmente creo mejor conveniente (ahora que lo he estudiado un poco) usar slack o gitter, que te parece?

**Comment by poseso** [comment]
slack me parece bien, enviame tu correo para agregarte o invitarte o si quieres crea el team e invitame a mi?

**Comment by ConsoleTVs** [comment]
Pasame tu correo y te añado

**Comment by poseso** [comment]
carlosmsanchez@gmail.com
