### ISSUE TITLE
Social Integration

### ISSUE THREAD

**Issue by anosim** [ConsoleTVs/Laralum#5]
it's really helpful effort.

waiting for your documentation and social authentication integration & Forums.

keep it up bro.

**Comment by ConsoleTVs** [comment]
Thanks a lot! We have a lot of work to do, docs aren't easy to write especially on a development application as everything is constantly changing, but we're doing our best to keep it clean!

In the following weeks you'll find yourself nice updates, containing first a laralum REST API that can be customized to show data from all your tables!

**Comment by ConsoleTVs** [comment]
Hello, I'm replying to make you happy today!

https://github.com/ConsoleTVs/Laralum/wiki/Social-Configuration

Here's the little docs you'll need to integrate social auth into laralum at today's release (2.1.2)
