### ISSUE TITLE
Blog View???

### ISSUE THREAD

**Issue by Yusuke002** [ConsoleTVs/Laralum#7]
Hello there, i have seen that the admin have the option of adding blogs,blog posts etc. But where the user can view them?

**Comment by ConsoleTVs** [comment]
Hello! All the "user" releated views are not done, so you'll need to use them!

Don't panic! I'm developing laralum 3.\* and it will already be done!

Meanwhile you'll need to work with the App\Blog model to output the results. It have lots of functions like: https://github.com/ConsoleTVs/Laralum/blob/master/app/Blog.php

**Comment by v4lerio** [comment]
Basic views for the blog are in resources/views/laralum/blogs but you have to call them properly where you wish.

**Comment by ConsoleTVs** [comment]
I would recommend you to create them anyway since all the relationships are already done, and the blog will adapt at your website's "theme"
