### ISSUE TITLE
Password for admin?

### ISSUE THREAD

**Issue by johnmorenov** [ConsoleTVs/Laralum#8]
Hi, congratulations for this very interesting admin panel for Laravel 5, I just installed it but I don't know the password for default admin user, I try to change it but Laravel display this error: "TokenMismatchException in VerifyCsrfToken.php line 67:", then, Is an existing error or only works with default admin password?

**Comment by ConsoleTVs** [comment]
Hello! Install laralum with composer create-project, then cisit your project url and click on the install laralum button or visit the /install location. You will then be able to create the admin user and some preferences!

**Comment by johnmorenov** [comment]
Thanks, I didn't have seen the Install button.
