### ISSUE TITLE
Can I integrate your admin panel for my Laravel 5 app?

### ISSUE THREAD

**Issue by johnmorenov** [ConsoleTVs/Laralum#9]
Hi, I already have a Dashboard in Laravel 5.3 with Metronic template, I was wondering if I can use your Admin Panel in order to integrate it with my app, for example, for assign page (or menus) permissions for specific users, if that's the case, What is the best way to do it?.

Thanks.

**Comment by ConsoleTVs** [comment]
Hey! Of course, the only thing is the page designs, that are currently static. 

The basic Laralum functions are found here: https://github.com/ConsoleTVs/Laralum/blob/master/app/Http/Controllers/Laralum/Laralum.php

Call them like this:

```
use Laralum;

Laralum::functionName()
```

Regarding to the other model features, you have the functions defined in the models. For example:
The User Model: https://github.com/ConsoleTVs/Laralum/blob/master/app/User.php

It have some functions like:

roles (return all roles from user)
isAdmin (return true / false)
hasPermission (return true if he have the permission)

and so on, you're free to check the model for theese functions, they can be user anywhere in your code!
